{
 "title": "E2E Dashboard",
 "tags": [ "qmmd,node" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node_job",
    "label": "CPU Exporter",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node_name",
    "label": "Host Name",
    "query": {
     "query": "label_values(node_uname_info{job=\"$node_job\"}, nodename)"
    }
   },
   {
    "name": "node_instance",
    "label": "CPU Exporter Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$node_job\", nodename=\"$node_name\"}, instance)"
    }
   },
   {
    "name": "nv_job",
    "label": "NVIDIA GPU Exporter",
    "query": {
     "query": "label_values(nvidia_smi_index, job)"
    }
   },
   {
    "name": "nv_gpu_exporter_instance",
    "label": "NVIDIA GPU Exporter Instance",
    "query": {
     "query": "label_values(nvidia_smi_index{job=\"$nv_job\"}, instance)"
    }
   },
   {
    "name": "nv_gpu_instance",
    "label": "NV GPU Instance",
    "query": {
     "query": "label_values(nvidia_smi_index{instance=\"$nv_gpu_exporter_instance\"}, uuid)"
    }
   },
   {
    "name": "nv_gpu_name",
    "label": "NVIDIA GPU Card",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info{uuid=\"$nv_gpu_instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qmmd_gpu_power_watts{domain=\"package\"}",
     "legendFormat": "PKG: {{device}}"
    },
    {
     "expr": "qmmd_gpu_power_watts{domain=\"gpu\"}",
     "legendFormat": "GPU: {{device}}"
    },
    { "expr": "npu_monitor_power{}", "legendFormat": "NPU: {{dev_id}}" },
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "$nv_gpu_name"
    }
   ]
  },
  {
   "title": "Package & GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "qmmd_gpu_power_watts{domain=\"package\"}",
     "legendFormat": "{{device}}:{{domain}}"
    },
    {
     "expr": "qmmd_gpu_power_watts{domain=\"gpu\"}",
     "legendFormat": "{{device}}:{{domain}}"
    },
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "$nv_gpu_name"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "qmmd_gpu_actual_frequency_hertz{freq_id=\"gt0\"}",
     "legendFormat": "{{device}}:{{freq_id}}: actual"
    },
    {
     "expr": "qmmd_gpu_actual_frequency_hertz{freq_id=\"gt1\"}",
     "legendFormat": "{{device}}:{{freq_id}}: actual"
    },
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "Gfx Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "Vid Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "SM Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "MEM Clk: $nv_gpu_name"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qmmd_gpu_actual_frequency_hertz{freq_id=\"gt0\"}",
     "legendFormat": "{{device}}:{{freq_id}}: actual"
    },
    {
     "expr": "qmmd_gpu_actual_frequency_hertz{freq_id=\"gt1\"}",
     "legendFormat": "{{device}}:{{freq_id}}: actual"
    },
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "Gfx Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "Vid Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "SM Clk: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "MEM Clk: $nv_gpu_name"
    }
   ]
  },
  {
   "title": "Per Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "qmmd_gpu_engine_utilization_ratio{}",
     "legendFormat": "{{device}}: {{engine}}"
    },
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "GPU %: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_utilization_decoder_ratio{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "DEC %: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_utilization_encoder_ratio{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "ENC %: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_utilization_jpeg_ratio{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "JPEG %: $nv_gpu_name"
    },
    {
     "expr": "nvidia_smi_utilization_ofa_ratio{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "OFA %: $nv_gpu_name"
    }
   ]
  },
  {
   "title": "INTC iGPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qmmd_gpu_memory_total_bytes{device=\"0000:00:02.0\", mem_type=\"smem\"}",
     "legendFormat": "SMEM"
    }
   ]
  },
  {
   "title": "INTC dGPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qmmd_gpu_memory_total_bytes{device=\"0000:05:00.0\", mem_type=\"vram\"}",
     "legendFormat": "VRAM"
    },
    {
     "expr": "qmmd_gpu_memory_total_bytes{device=\"0000:05:00.0\", mem_type=\"smem\"}",
     "legendFormat": "SMEM"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "qmmd_gpu_memory_used_bytes{mem_type=\"smem\"}",
     "legendFormat": "{{device}}:{{mem_type}}"
    },
    {
     "expr": "qmmd_gpu_memory_used_bytes{mem_type=\"vram\"}",
     "legendFormat": "{{device}}:{{mem_type}}"
    },
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "$nv_gpu_name"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "qmmd_gpu_memory_used_bytes{mem_type=\"smem\"} / qmmd_gpu_memory_total_bytes{mem_type=\"smem\"}",
     "legendFormat": "{{device}}:{{mem_type}}"
    },
    {
     "expr": "qmmd_gpu_memory_used_bytes{mem_type=\"vram\"} / qmmd_gpu_memory_total_bytes{mem_type=\"vram\"}",
     "legendFormat": "{{device}}:{{mem_type}}"
    },
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$nv_gpu_instance\"} / nvidia_smi_memory_total_bytes{uuid=\"$nv_gpu_instance\"}",
     "legendFormat": "$nv_gpu_name"
    }
   ]
  },
  {
   "title": "NVIDIA dGPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nvidia_smi_memory_total_bytes", "legendFormat": "SMEM" }
   ]
  },
  { "title": "NPU Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "NPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "npu_monitor_temperature{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "npu_monitor_power{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "DPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "npu_monitor_freq_hz{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "DPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "npu_monitor_freq_hz{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "npu_util{} / 100", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Tile Config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "npu_tile_config{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "npu_memory_util{} * (1024 * 1024)",
     "legendFormat": "NPU: {{dev_id}}"
    }
   ]
  },
  {
   "title": "NPU Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "npu_memory_bandwidth{} * (1024 * 1024)",
     "legendFormat": "NPU: {{dev_id}}"
    }
   ]
  },
  { "title": "CPU | Memory | Storage ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node_instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node_instance\",job=\"$node_job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node_instance\", job=\"$node_job\"} / node_memory_MemTotal_bytes{instance=\"$node_instance\", job=\"$node_job\"})) * 100, 0)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node_instance\",job=\"$node_job\"} - node_memory_SwapFree_bytes{instance=\"$node_instance\",job=\"$node_job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node_instance\",job=\"$node_job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node_instance\", job=\"$node_job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node_instance\", job=\"$node_job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node_instance\", job=\"$node_job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node_instance\",job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node_instance\",job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node_instance\",job=\"$node_job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node_instance\",job=\"$node_job\"} - node_boot_time_seconds{instance=\"$node_instance\",job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "CPU Frequency Scaling",
   "type": "timeseries",
   "description": "Real-time CPU frequency scaling per core, including average minimum and maximum allowed scaling frequencies",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"$node_instance\",job=\"$node_job\"}",
     "legendFormat": "CPU {{ cpu }}"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_max_hertz{instance=\"$node_instance\",job=\"$node_job\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_min_hertz{instance=\"$node_instance\",job=\"$node_job\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node_instance\",job=\"$node_job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node_instance\",job=\"$node_job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  }
 ]
}